-- Add sql statments to insert values

+INSERT INTO "VCHAWLA3"."PERSON" (PER_ID, PER_FIRSTNAME, PER_LASTNAME, PER_DATEOFBIRTH, PER_ADDRESS, PER_SEX, PER_PASSWORD) VALUES ('1', 'Sheldon', 'Cooper', TO_DATE('1984-05-26 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), '2500 Sacramento, Apt 903, Santa Cruz, CA - 90021', 'M', 'password');
+INSERT INTO "VCHAWLA3"."PERSON" (PER_ID, PER_FIRSTNAME, PER_LASTNAME, PER_DATEOFBIRTH, PER_ADDRESS, PER_SEX, PER_PASSWORD) VALUES ('2', 'Leonard', 'Hofstader', TO_DATE('1989-04-19 00:01:36', 'YYYY-MM-DD HH24:MI:SS'), '2500 Sacramento, Apt 904, Santa Cruz, CA - 90021', 'M', 'password');
+INSERT INTO "VCHAWLA3"."PERSON" (PER_ID, PER_FIRSTNAME, PER_LASTNAME, PER_DATEOFBIRTH, PER_ADDRESS, PER_SEX, PER_PASSWORD) VALUES ('3', 'Penny', 'Hofstader', TO_DATE('1990-12-25 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), '2500 Sacramento, Apt 904, Santa Cruz, CA - 90021', 'F', 'password');
+INSERT INTO "VCHAWLA3"."PERSON" (PER_ID, PER_FIRSTNAME, PER_LASTNAME, PER_DATEOFBIRTH, PER_ADDRESS, PER_SEX, PER_PASSWORD) VALUES ('4', 'Amy', 'Farrahfowler', TO_DATE('1992-06-15 00:02:35', 'YYYY-MM-DD HH24:MI:SS'), '2500 Sacramento, Apt 905, Santa Cruz, CA - 90021', 'F', 'password');
+
+INSERT INTO "VCHAWLA3"."PATIENT" (PAT_PERSON, PAT_SICK) VALUES ('1', '1');
+INSERT INTO "VCHAWLA3"."PATIENT" (PAT_PERSON, PAT_SICK) VALUES ('2', '1');
+INSERT INTO "VCHAWLA3"."PATIENT" (PAT_PERSON, PAT_SICK) VALUES ('3', '0');
+INSERT INTO "VCHAWLA3"."PATIENT" (PAT_PERSON, PAT_SICK) VALUES ('4', '0');
+
+INSERT INTO "VCHAWLA3"."HEALTH_SUPPORTER" (HS_SUPPORTER, HS_PATIENT, HS_DATEAUTHORIZED) VALUES ('2', '1', TO_DATE('2016-10-21 00:23:45', 'YYYY-MM-DD HH24:MI:SS'));
+INSERT INTO "VCHAWLA3"."HEALTH_SUPPORTER" (HS_SUPPORTER, HS_PATIENT, HS_DATEAUTHORIZED) VALUES ('4', '1', TO_DATE('2016-10-21 00:00:00', 'YYYY-MM-DD HH24:MI:SS'));
+INSERT INTO "VCHAWLA3"."HEALTH_SUPPORTER" (HS_SUPPORTER, HS_PATIENT, HS_DATEAUTHORIZED) VALUES ('3', '2', TO_DATE('2016-10-09 00:24:16', 'YYYY-MM-DD HH24:MI:SS'));
+INSERT INTO "VCHAWLA3"."HEALTH_SUPPORTER" (HS_SUPPORTER, HS_PATIENT, HS_DATEAUTHORIZED) VALUES ('4', '3', TO_DATE('2016-10-21 00:00:00', 'YYYY-MM-DD HH24:MI:SS'));