INSERT INTO "PERSON" (PER_ID, PER_FIRSTNAME, PER_LASTNAME, PER_DATEOFBIRTH, PER_ADDRESS, PER_SEX, PER_PASSWORD) VALUES ('5', 'Tom', 'Jones', TO_DATE('1992-06-15 00:02:35', 'YYYY-MM-DD HH24:MI:SS'), '2500 Sacramento, Apt 905, Santa Cruz, CA - 90021', 'M', 'password');
INSERT INTO "PERSON" (PER_ID, PER_FIRSTNAME, PER_LASTNAME, PER_DATEOFBIRTH, PER_ADDRESS, PER_SEX, PER_PASSWORD) VALUES ('6', 'Jane', 'Doe', TO_DATE('1992-06-15 00:02:35', 'YYYY-MM-DD HH24:MI:SS'), '2500 Sacramento, Apt 905, Santa Cruz, CA - 90021', 'F', 'password');
INSERT INTO "PERSON" (PER_ID, PER_FIRSTNAME, PER_LASTNAME, PER_DATEOFBIRTH, PER_ADDRESS, PER_SEX, PER_PASSWORD) VALUES ('7', 'Patrick', 'Star', TO_DATE('1986-02-26 00:02:35', 'YYYY-MM-DD HH24:MI:SS'), '120 Conch Street, Bikini Bottom, Pacific Ocean', 'M', 'password');
INSERT INTO "PERSON" (PER_ID, PER_FIRSTNAME, PER_LASTNAME, PER_DATEOFBIRTH, PER_ADDRESS, PER_SEX, PER_PASSWORD) VALUES ('8', 'Spongebob', 'Squarepants', TO_DATE('1986-07-14 00:02:35', 'YYYY-MM-DD HH24:MI:SS'), '124 Conch Street Bikini Bottom, Pacific Ocean', 'M', 'password');
INSERT INTO "PERSON" (PER_ID, PER_FIRSTNAME, PER_LASTNAME, PER_DATEOFBIRTH, PER_ADDRESS, PER_SEX, PER_PASSWORD) VALUES ('9', 'Squidward', 'Tentacles', TO_DATE('1965-10-09 00:02:35', 'YYYY-MM-DD HH24:MI:SS'), '122 Conch Street Bikini Bottom, Pacific Ocean', 'M', 'password');

INSERT INTO "PATIENT" (PAT_PERSON, PAT_SICK) VALUES ('5', '1');
INSERT INTO "PATIENT" (PAT_PERSON, PAT_SICK) VALUES ('6', '0');
--Keeping Patrick Star as a well patient but adding disease later to check trigger
INSERT INTO "PATIENT" (PAT_PERSON, PAT_SICK) VALUES ('7', '0');
INSERT INTO "PATIENT" (PAT_PERSON, PAT_SICK) VALUES ('8', '1');
INSERT INTO "PATIENT" (PAT_PERSON, PAT_SICK) VALUES ('9', '0');

INSERT INTO "HEALTH_SUPPORTER" (HS_SUPPORTER, HS_PATIENT, HS_DATEAUTHORIZED) VALUES ('6', '5', TO_DATE('2016-10-21 00:00:00', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO "HEALTH_SUPPORTER" (HS_SUPPORTER, HS_PATIENT, HS_DATEAUTHORIZED) VALUES ('7', '8', TO_DATE('2016-10-21 00:00:00', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO "HEALTH_SUPPORTER" (HS_SUPPORTER, HS_PATIENT, HS_DATEAUTHORIZED) VALUES ('9', '7', TO_DATE('2016-10-21 00:00:00', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO "HEALTH_SUPPORTER" (HS_SUPPORTER, HS_PATIENT, HS_DATEAUTHORIZED) VALUES ('9', '8', TO_DATE('2016-10-21 00:00:00', 'YYYY-MM-DD HH24:MI:SS'));

INSERT INTO "DISEASE" (DIS_DISEASENAME) VALUES ('Suds');

INSERT INTO "DIAGNOSIS" (DI_PATIENT, DI_DISEASENAME) VALUES ('5', 'Heart Disease');
INSERT INTO "DIAGNOSIS" (DI_PATIENT, DI_DISEASENAME) VALUES ('7', 'Suds');
INSERT INTO "DIAGNOSIS" (DI_PATIENT, DI_DISEASENAME) VALUES ('8', 'Suds');

INSERT INTO "HEALTH_OBSERVATION_TYPE" (HOT_ID, HOT_NAME, HOT_DISEASE, HOT_UPPERLIMIT, HOT_LOWERLIMIT, HOT_FREQUENCY) VALUES ('17', 'Weight', 'Suds', '10', '5', '5');
INSERT INTO "HEALTH_OBSERVATION_TYPE" (HOT_ID, HOT_NAME, HOT_DISEASE, HOT_UPPERLIMIT, HOT_FREQUENCY) VALUES ('17', 'Mood', 'Suds', '1', '7');
INSERT INTO "HEALTH_OBSERVATION_TYPE" (HOT_ID, HOT_NAME, HOT_DISEASE, HOT_UPPERLIMIT, HOT_LOWERLIMIT, HOT_FREQUENCY) VALUES ('17', 'Temperature', 'Suds', '100', '95', '1');